### ISSUE TITLE
Nodes do not appear when adding textures and when adding objects

### ISSUE THREAD

**Issue by Lindsaydoodle** [chopstyix/Blender-Quixel-Bridge#2]
![image](https://github.com/chopstyix/Blender-Quixel-Bridge/assets/45480043/3efe6e67-ac52-4176-8845-2b7de1048fd0)
Hi, thanks for working on this addon, but there is a problem that nodes with materials and so on do not appear. Maybe there's something wrong with me, but I don't understand where 

BLENDER 4.0.2 steam version \ BLENDER 4.0.2 blender.org tested

**Comment by chopstyix** [comment]
Hey, thanks for submitting!

How did you install the add-on?
I was able to replicate this issue w/ v4.0.2 via Steam. It turns out I had a duplicate MSLink folder causing a conflict with the add-on.

I got it to work by extracting the contents of the .zip file to the startup folder, it should look like this:
_%appdata%\Blender Foundation\Blender\4.0\scripts\startup\MSLink_

![Screenshot 2023-12-26 234123](https://github.com/chopstyix/Blender-Quixel-Bridge/assets/76865097/636bf45e-854b-4f4e-a503-07201b6935d3)

**Comment by Lindsaydoodle** [comment]
> Эй, спасибо за отправку!
> 
> Как вы установили дополнение? Мне удалось воспроизвести эту проблему с версией 4.0.2 через Steam. Оказывается, у меня была дубликат папки MSLink, вызывающий конфликт с надстройкой.
> 
> Я заставил его работать, извлекая содержимое файла .zip в папку автозагрузки. Он должен выглядеть так: _%appdata%\Blender Foundation\Blender\4.0\scripts\startup\MSLink_
> 
> ![Скриншот 26.12.2023 234123](https://private-user-images.githubusercontent.com/76865097/292983874-636bf45e-854b-4f4e-a503-07201b6935d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDUyMDIsIm5iZiI6MTcwNzQwNDkwMiwicGF0aCI6Ii83Njg2NTA5Ny8yOTI5ODM4NzQtNjM2YmY0NWUtODU0Yi00ZjRlLWE1MDMtMDcyMDFiNjkzNWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE1MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzM2U2NGI3MGNlM2FjZTliZTU1YzIwYTY0NjNhOWNmY2I3YWViN2NjMDVmNzUyMTAwMzFmOTQyZmMwZWEyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gx8nxCu4c9VclRPWh4ZCn4ahBe9ryXhEGCBwneq33Qg)

you fixed <3 ty
